FROM codecheck/ruby
MAINTAINER Dan Sosedoff "dan@doejo.com"

RUN gem install sandi_meter \
                simplecov \
                flog \
                cane \
                brakeman \
                ruby-lint \
                rubocop \
                rails_best_practices